from pathlib import Path

from reports.pdf_generator import PDFGenerator

from utils.charts import ChartGenerator
from utils.chart_exporter import ChartExporter


class ReportGenerator:

    @staticmethod
    def generate(df, profile, ai_report):
        """
        Generate the Enterprise AI PDF Report.

        Parameters
        ----------
        df : pandas.DataFrame
            Uploaded dataset.

        profile : dict
            Dataset profile generated by DataProfiler.

        ai_report : str
            Gemini AI generated analysis.

        Returns
        -------
        str
            Path to the generated PDF report.
        """

        # -----------------------------
        # Create output directory
        # -----------------------------
        output_dir = Path("reports/output")
        output_dir.mkdir(parents=True, exist_ok=True)

        charts = []

        # -----------------------------
        # Generate charts
        # -----------------------------
        for title, fig in ChartGenerator.generate_all(df):

            filename = (
                title.lower()
                .replace(" ", "_")
                .replace("-", "_")
                .replace("/", "_")
                + ".png"
            )

            image_path = ChartExporter.save(
                fig,
                filename
            )

            charts.append(
                (
                    title,
                    image_path
                )
            )

        # -----------------------------
        # Generate PDF
        # -----------------------------
        pdf_path = output_dir / "AI_Report.pdf"

        PDFGenerator.generate(
            profile=profile,
            ai_report=ai_report,
            charts=charts,
            filename=str(pdf_path)
        )

        return str(pdf_path)